# Schema for the configuration files of the assessment module.
assessment.settings:
  type: config_object
  label: 'assessment settings'
  mapping:
    example:
      type: string
      label: 'Example'
