# Schema for the configuration files of the assessment module.
assessment.settings:
  type: config_object
  label: 'assessment settings'
  mapping:
    title:
      type: string
      label: 'Title'
    text:
      type: text
      label: 'Text'
    format:
      type: string
      label: 'Format'
    display:
      type: boolean
      label: 'Display'